// Name translations extracted from w3gjs/dist/lib/mappings.js
// Values use prefixes: u_ = unit, p_ = upgrade, a_ = ability, b_ = building

export const UNIT_NAMES: Record<string, string> = {
  // Human
  hfoo: 'u_Footman',
  hkni: 'u_Knight',
  hmpr: 'u_Priest',
  hmtm: 'u_Mortar Team',
  hpea: 'u_Peasant',
  hrif: 'u_Rifleman',
  hsor: 'u_Sorceress',
  hmtt: 'u_Siege Engine',
  hrtt: 'u_Siege Engine',
  hgry: 'u_Gryphon Rider',
  hgyr: 'u_Flying Machine',
  hspt: 'u_Spell Breaker',
  hdhw: 'u_Dragonhawk Rider',
  // Night Elf
  ebal: 'u_Glaive Thrower',
  echm: 'u_Chimaera',
  edoc: 'u_Druid of the Claw',
  edot: 'u_Druid of the Talon',
  ewsp: 'u_Wisp',
  esen: 'u_Huntress',
  earc: 'u_Archer',
  edry: 'u_Dryad',
  ehip: 'u_Hippogryph',
  emtg: 'u_Mountain Giant',
  efdr: 'u_Faerie Dragon',
  // Orc
  ocat: 'u_Demolisher',
  odoc: 'u_Troll Witch Doctor',
  ogru: 'u_Grunt',
  ohun: 'u_Troll Headhunter/Berserker',
  otbk: 'u_Troll Headhunter/Berserker',
  okod: 'u_Kodo Beast',
  opeo: 'u_Peon',
  orai: 'u_Raider',
  oshm: 'u_Shaman',
  otau: 'u_Tauren',
  owyv: 'u_Wind Rider',
  ospw: 'u_Spirit Walker',
  ospm: 'u_Spirit Walker',
  otbr: 'u_Troll Batrider',
  // Undead
  uaco: 'u_Acolyte',
  uabo: 'u_Abomination',
  uban: 'u_Banshee',
  ucry: 'u_Crypt Fiend',
  ufro: 'u_Frost Wyrm',
  ugar: 'u_Gargoyle',
  ugho: 'u_Ghoul',
  unec: 'u_Necromancer',
  umtw: 'u_Meatwagon',
  ushd: 'u_Shade',
  uobs: 'u_Obsidian Statue',
  ubsp: 'u_Destroyer',
  // Neutral / Creeps
  nskm: 'u_Skeletal Marksman',
  nskf: 'u_Burning Archer',
  nban: 'u_Bandit',
  nrog: 'u_Rogue',
  nenf: 'u_Enforcer',
  nass: 'u_Assassin',
  nbdk: 'u_Black Drake',
  nrdk: 'u_Red Dragon Whelp',
  nbdr: 'u_Black Dragon Whelp',
  nrdr: 'u_Red Drake',
  nbwm: 'u_Black Dragon',
  nrwm: 'u_Red Dragon',
  nadr: 'u_Blue Dragon',
  nadw: 'u_Blue Dragon Whelp',
  nadk: 'u_Blue Drake',
  nbzd: 'u_Bronze Dragon',
  nbzk: 'u_Bronze Drake',
  nbzw: 'u_Bronze Dragon Whelp',
  ngrd: 'u_Green Dragon',
  ngdk: 'u_Green Drake',
  ngrw: 'u_Green Dragon Whelp',
  ncea: 'u_Centaur Archer',
  ncen: 'u_Centaur Outrunner',
  ncer: 'u_Centaur Drudge',
  ndth: 'u_Dark Troll High Priest',
  ndtp: 'u_Dark Troll Shadow Priest',
  ndtb: 'u_Dark Troll Berserker',
  ndtw: 'u_Dark Troll Warlord',
  ndtr: 'u_Dark Troll',
  ndtt: 'u_Dark Troll Trapper',
  nfsh: 'u_Forest Troll High Priest',
  nfsp: 'u_Forest Troll Shadow Priest',
  nftr: 'u_Forest Troll',
  nftb: 'u_Forest Troll Berserker',
  nftt: 'u_Forest Troll Trapper',
  nftk: 'u_Forest Troll Warlord',
  ngrk: 'u_Mud Golem',
  ngir: 'u_Goblin Shredder',
  nfrs: 'u_Furbolg Shaman',
  ngna: 'u_Gnoll Poacher',
  ngns: 'u_Gnoll Assassin',
  ngno: 'u_Gnoll',
  ngnb: 'u_Gnoll Brute',
  ngnw: 'u_Gnoll Warden',
  ngnv: 'u_Gnoll Overseer',
  ngsp: 'u_Goblin Sapper',
  nhrr: 'u_Harpy Rogue',
  nhrw: 'u_Harpy Windwitch',
  nits: 'u_Ice Troll Berserker',
  nitt: 'u_Ice Troll Trapper',
  nkob: 'u_Kobold',
  nkog: 'u_Kobold Geomancer',
  nthl: 'u_Thunder Lizard',
  nmfs: 'u_Murloc Flesheater',
  nmrr: 'u_Murloc Huntsman',
  nowb: 'u_Wildkin',
  nrzm: 'u_Razormane Medicine Man',
  nnwa: 'u_Nerubian Warrior',
  nnwl: 'u_Nerubian Webspinner',
  nogr: 'u_Ogre Warrior',
  nogm: 'u_Ogre Mauler',
  nogl: 'u_Ogre Lord',
  nomg: 'u_Ogre Magi',
  nrvs: 'u_Frost Revenant',
  nslf: 'u_Sludge Flinger',
  nsts: 'u_Satyr Shadowdancer',
  nstl: 'u_Satyr Soulstealer',
  nzep: 'u_Goblin Zeppelin',
  ntrt: 'u_Giant Sea Turtle',
  nlds: 'u_Makrura Deepseer',
  nlsn: 'u_Makrura Snapper',
  nmsn: "u_Mur'gul Snarecaster",
  nscb: 'u_Spider Crab Shorecrawler',
  nbot: 'u_Transport Ship',
  nbdm: 'u_Blue Dragonspawn Meddler',
  nmgw: 'u_Magnataur Warrior',
  nanb: 'u_Barbed Arachnathid',
  nanm: 'u_Barbed Arachnathid',
  nfps: 'u_Polar Furbolg Shaman',
  nmgv: 'u_Magic Vault',
  nitb: 'u_Icy Treasure Box',
  npfl: 'u_Fel Beast',
  ndrd: 'u_Draenei Darkslayer',
  ndrm: 'u_Draenei Disciple',
  nvdw: 'u_Voidwalker',
  nvdg: 'u_Greater Voidwalker',
  nnht: 'u_Nether Dragon Hatchling',
  nndk: 'u_Nether Drake',
  nndr: 'u_Nether Dragon',
}

export const UPGRADE_NAMES: Record<string, string> = {
  Rhss: 'p_Control Magic',
  Rhme: 'p_Swords',
  Rhra: 'p_Gunpowder',
  Rhar: 'p_Plating',
  Rhla: 'p_Armor',
  Rhac: 'p_Masonry',
  Rhgb: 'p_Flying Machine Bombs',
  Rhlh: 'p_Lumber Harvesting',
  Rhde: 'p_Defend',
  Rhan: 'p_Animal War Training',
  Rhpt: 'p_Priest Training',
  Rhst: 'p_Sorceress Training',
  Rhri: 'p_Long Rifles',
  Rhse: 'p_Magic Sentry',
  Rhfl: 'p_Flare',
  Rhhb: 'p_Storm Hammers',
  Rhrt: 'p_Barrage',
  Rhpm: 'p_Backpack',
  Rhfc: 'p_Flak Cannons',
  Rhfs: 'p_Fragmentation Shards',
  Rhcd: 'p_Cloud',
  Resm: 'p_Strength of the Moon',
  Resw: 'p_Strength of the Wild',
  Rema: 'p_Moon Armor',
  Rerh: 'p_Reinforced Hides',
  Reuv: 'p_Ultravision',
  Renb: "p_Nature's Blessing",
  Reib: 'p_Improved Bows',
  Remk: 'p_Marksmanship',
  Resc: 'p_Sentinel',
  Remg: 'p_Upgrade Moon Glaive',
  Redt: 'p_Druid of the Talon Training',
  Redc: 'p_Druid of the Claw Training',
  Resi: 'p_Abolish Magic',
  Reht: 'p_Hippogryph Taming',
  Recb: 'p_Corrosive Breath',
  Repb: 'p_Vorpal Blades',
  Rers: 'p_Resistant Skin',
  Rehs: 'p_Hardened Skin',
  Reeb: 'p_Mark of the Claw',
  Reec: 'p_Mark of the Talon',
  Rews: 'p_Well Spring',
  Repm: 'p_Backpack',
  Roch: 'p_Chaos',
  Rome: 'p_Melee Weapons',
  Rora: 'p_Ranged Weapons',
  Roar: 'p_Armor',
  Rwdm: 'p_War Drums Damage Increase',
  Ropg: 'p_Pillage',
  Robs: 'p_Berserker Strength',
  Rows: 'p_Pulverize',
  Roen: 'p_Ensnare',
  Rovs: 'p_Envenomed Spears',
  Rowd: 'p_Witch Doctor Training',
  Rost: 'p_Shaman Training',
  Rosp: 'p_Spiked Barricades',
  Rotr: 'p_Troll Regeneration',
  Rolf: 'p_Liquid Fire',
  Ropm: 'p_Backpack',
  Rowt: 'p_Spirit Walker Training',
  Robk: 'p_Berserker Upgrade',
  Rorb: 'p_Reinforced Defenses',
  Robf: 'p_Burning Oil',
  Rusp: 'p_Destroyer Form',
  Rume: 'p_Unholy Strength',
  Rura: 'p_Creature Attack',
  Ruar: 'p_Unholy Armor',
  Rucr: 'p_Creature Carapace',
  Ruac: 'p_Cannibalize',
  Rugf: 'p_Ghoul Frenzy',
  Ruwb: 'p_Web',
  Rusf: 'p_Stone Form',
  Rune: 'p_Necromancer Training',
  Ruba: 'p_Banshee Training',
  Rufb: 'p_Freezing Breath',
  Rusl: 'p_Skeletal Longevity',
  Rupc: 'p_Disease Cloud',
  Rusm: 'p_Skeletal Mastery',
  Rubu: 'p_Burrow',
  Ruex: 'p_Exhume Corpses',
  Rupm: 'p_Backpack',
}

export const ABILITY_NAMES: Record<string, string> = {
  AHbz: 'a_Archmage:Blizzard',
  AHwe: 'a_Archmage:Summon Water Elemental',
  AHab: 'a_Archmage:Brilliance Aura',
  AHmt: 'a_Archmage:Mass Teleport',
  AHtb: 'a_Mountain King:Storm Bolt',
  AHtc: 'a_Mountain King:Thunder Clap',
  AHbh: 'a_Mountain King:Bash',
  AHav: 'a_Mountain King:Avatar',
  AHhb: 'a_Paladin:Holy Light',
  AHds: 'a_Paladin:Divine Shield',
  AHad: 'a_Paladin:Devotion Aura',
  AHre: 'a_Paladin:Resurrection',
  AHdr: 'a_Blood Mage:Siphon Mana',
  AHfs: 'a_Blood Mage:Flame Strike',
  AHbn: 'a_Blood Mage:Banish',
  AHpx: 'a_Blood Mage:Summon Phoenix',
  AEmb: 'a_Demon Hunter:Mana Burn',
  AEim: 'a_Demon Hunter:Immolation',
  AEev: 'a_Demon Hunter:Evasion',
  AEme: 'a_Demon Hunter:Metamorphosis',
  AEer: 'a_Keeper of the Grove:Entangling Roots',
  AEfn: 'a_Keeper of the Grove:Force of Nature',
  AEah: 'a_Keeper of the Grove:Thorns Aura',
  AEtq: 'a_Keeper of the Grove:Tranquility',
  AEst: 'a_Priestess of the Moon:Scout',
  AHfa: 'a_Priestess of the Moon:Searing Arrows',
  AEar: 'a_Priestess of the Moon:Trueshot Aura',
  AEsf: 'a_Priestess of the Moon:Starfall',
  AEbl: 'a_Warden:Blink',
  AEfk: 'a_Warden:Fan of Knives',
  AEsh: 'a_Warden:Shadow Strike',
  AEsv: 'a_Warden:Spirit of Vengeance',
  AOwk: 'a_Blademaster:Wind Walk',
  AOmi: 'a_Blademaster:Mirror Image',
  AOcr: 'a_Blademaster:Critical Strike',
  AOww: 'a_Blademaster:Bladestorm',
  AOcl: 'a_Far Seer:Chain Lightning',
  AOfs: 'a_Far Seer:Far Sight',
  AOsf: 'a_Far Seer:Feral Spirit',
  AOeq: 'a_Far Seer:Earth Quake',
  AOsh: 'a_Tauren Chieftain:Shockwave',
  AOae: 'a_Tauren Chieftain:Endurance Aura',
  AOws: 'a_Tauren Chieftain:War Stomp',
  AOre: 'a_Tauren Chieftain:Reincarnation',
  AOhw: 'a_Shadow Hunter:Healing Wave',
  AOhx: 'a_Shadow Hunter:Hex',
  AOsw: 'a_Shadow Hunter:Serpent Ward',
  AOvd: 'a_Shadow Hunter:Big Bad Voodoo',
  AUdc: 'a_Death Knight:Death Coil',
  AUdp: 'a_Death Knight:Death Pact',
  AUau: 'a_Death Knight:Unholy Aura',
  AUan: 'a_Death Knight:Animate Dead',
  AUcs: 'a_Dreadlord:Carrion Swarm',
  AUsl: 'a_Dreadlord:Sleep',
  AUav: 'a_Dreadlord:Vampiric Aura',
  AUin: 'a_Dreadlord:Inferno',
  AUfn: 'a_Lich:Frost Nova',
  AUfa: 'a_Lich:Frost Armor',
  AUfu: 'a_Lich:Frost Armor',
  AUdr: 'a_Lich:Dark Ritual',
  AUdd: 'a_Lich:Death and Decay',
  AUim: 'a_Crypt Lord:Impale',
  AUts: 'a_Crypt Lord:Spiked Carapace',
  AUcb: 'a_Crypt Lord:Carrion Beetles',
  AUls: 'a_Crypt Lord:Locust Swarm',
  ANbf: 'a_Pandaren Brewmaster:Breath of Fire',
  ANdb: 'a_Pandaren Brewmaster:Drunken Brawler',
  ANdh: 'a_Pandaren Brewmaster:Drunken Haze',
  ANef: 'a_Pandaren Brewmaster:Storm Earth and Fire',
  ANdr: 'a_Dark Ranger:Life Drain',
  ANsi: 'a_Dark Ranger:Silence',
  ANba: 'a_Dark Ranger:Black Arrow',
  ANch: 'a_Dark Ranger:Charm',
  ANms: 'a_Naga Sea Witch:Mana Shield',
  ANfa: 'a_Naga Sea Witch:Frost Arrows',
  ANfl: 'a_Naga Sea Witch:Forked Lightning',
  ANto: 'a_Naga Sea Witch:Tornado',
  ANrf: 'a_Pit Lord:Rain of Fire',
  ANca: 'a_Pit Lord:Cleaving Attack',
  ANht: 'a_Pit Lord:Howl of Terror',
  ANdo: 'a_Pit Lord:Doom',
  ANsg: 'a_Beastmaster:Summon Bear',
  ANsq: 'a_Beastmaster:Summon Quilbeast',
  ANsw: 'a_Beastmaster:Summon Hawk',
  ANst: 'a_Beastmaster:Stampede',
  ANeg: 'a_Goblin Tinker:Engineering Upgrade',
  ANcs: 'a_Goblin Tinker:Cluster Rockets',
  ANc1: 'a_Goblin Tinker:Cluster Rockets',
  ANc2: 'a_Goblin Tinker:Cluster Rockets',
  ANc3: 'a_Goblin Tinker:Cluster Rockets',
  ANsy: 'a_Goblin Tinker:Pocket Factory',
  ANs1: 'a_Goblin Tinker:Pocket Factory',
  ANs2: 'a_Goblin Tinker:Pocket Factory',
  ANs3: 'a_Goblin Tinker:Pocket Factory',
  ANrg: 'a_Goblin Tinker:Robo-Goblin',
  ANg1: 'a_Goblin Tinker:Robo-Goblin',
  ANg2: 'a_Goblin Tinker:Robo-Goblin',
  ANg3: 'a_Goblin Tinker:Robo-Goblin',
  ANic: 'a_Firelord:Incinerate',
  ANia: 'a_Firelord:Incinerate',
  ANso: 'a_Firelord:Soul Burn',
  ANlm: 'a_Firelord:Summon Lava Spawn',
  ANvc: 'a_Firelord:Volcano',
  ANhs: 'a_Goblin Alchemist:Healing Spray',
  ANab: 'a_Goblin Alchemist:Acid Bomb',
  ANcr: 'a_Goblin Alchemist:Chemical Rage',
  ANtm: 'a_Goblin Alchemist:Transmute',
}

export const BUILDING_NAMES: Record<string, string> = {
  // Human
  hhou: 'Farm',
  halt: 'Altar of Kings',
  harm: 'Workshop',
  hars: 'Arcane Sanctum',
  hbar: 'Barracks',
  hbla: 'Blacksmith',
  hgra: 'Gryphon Aviary',
  hwtw: 'Scout Tower',
  hvlt: 'Arcane Vault',
  hlum: 'Lumber Mill',
  htow: 'Town Hall',
  hkee: 'Keep',
  hcas: 'Castle',
  hctw: 'Cannon Tower',
  hgtw: 'Guard Tower',
  hatw: 'Arcane Tower',
  // Night Elf
  etrp: 'Ancient Protector',
  etol: 'Tree of Life',
  edob: "Hunter's Hall",
  eate: 'Altar of Elders',
  eden: 'Ancient of Wonders',
  eaoe: 'Ancient of Lore',
  eaom: 'Ancient of War',
  eaow: 'Ancient of Wind',
  edos: 'Chimaera Roost',
  emow: 'Moon Well',
  etoa: 'Tree of Ages',
  etoe: 'Tree of Eternity',
  // Orc
  oalt: 'Altar of Storms',
  obar: 'Barracks',
  obea: 'Beastiary',
  ofor: 'War Mill',
  ogre: 'Great Hall',
  osld: 'Spirit Lodge',
  otrb: 'Orc Burrow',
  orbr: 'Reinforced Orc Burrow',
  otto: 'Tauren Totem',
  ovln: 'Voodoo Lounge',
  owtw: 'Watch Tower',
  ofrt: 'Fortress',
  ostr: 'Stronghold',
  // Undead
  uaod: 'Altar of Darkness',
  unpl: 'Necropolis',
  usep: 'Crypt',
  utod: 'Temple of the Damned',
  utom: 'Tomb of Relics',
  ugol: 'Haunted Gold Mine',
  uzig: 'Ziggurat',
  ubon: 'Boneyard',
  usap: 'Sacrificial Pit',
  uslh: 'Slaughterhouse',
  ugrv: 'Graveyard',
  unp1: 'Halls of the Dead',
  unp2: 'Black Citadel',
  uzg1: 'Spirit Tower',
  uzg2: 'Nerubian Tower',
}
